### ISSUE TITLE
Initialize Backend (Spring Boot + PostgreSQL)

### ISSUE THREAD

**Issue by jimmsi** [jimmsi/receptfix#1]
Set up the backend for the project using Spring Boot and PostgreSQL

1. Create a new Spring Boot project

Initialize a new Spring Boot project with the necessary dependencies:
spring-boot-starter-web (for REST API)
spring-boot-starter-data-jpa (for Hibernate)
postgresql (PostgreSQL driver)
spring-boot-starter-validation (for input validation)
spring-boot-devtools (for hot reload during development)

2. Set up PostgreSQL using Docker

Add a docker-compose.yml file for PostgreSQL:

```
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: receptfix-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: receptfix
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
```

Ensure Spring Boot connects to the database using:

```
SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/receptfix
SPRING_DATASOURCE_USERNAME=user
SPRING_DATASOURCE_PASSWORD=password
```

3. Add .gitignore for Java/Spring Boot

Test everything
